[package]
name = "ty-backend-admin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.3.1"
anyhow = "1.0.71"
serde = { version = "1.0.166", features = ["derive"] }
thiserror = "1.0.43"
